Repository CodeForAfrica/PesaYetu, pull requests merged in 2021-08, with the labels that each got.

#39 [Feature] County Insights Card + Section
  src/assets/images/adomas-aleno-unsplash.png
  src/assets/images/adomas-aleno-unsplash@2x.png
  src/assets/images/josh-sorenson-unsplash.png
  src/assets/images/josh-sorenson-unsplash@2x.png
  src/assets/images/marita-kavelashvili-unsplash.png
  src/assets/images/marita-kavelashvili-unsplash@2x.png
  src/components/InsightCard/index.js
  src/components/InsightCard/index.stories.js
  src/components/InsightCard/useStyles.js
  src/components/InsightsData/index.js
  src/components/InsightsData/index.stories.js
  src/components/InsightsData/useStyles.js
  src/config.js
  src/functions/formatBlocksForSections.js
  src/pages/index.js
Labels: enhancement

#44 [Feature] Reusable Card Component
  src/components/Card/index.js
  src/components/Card/index.stories.js
  src/components/Card/useStyles.js
  src/components/DataVisualCard/index.js
  src/components/DataVisualCard/useStyles.js
  src/components/DataVisuals/index.js
  src/components/ExploreCard/index.js
  src/components/ExploreCard/useStyles.js
  src/components/InsightCard/index.js
  src/components/InsightCard/useStyles.js
  src/components/InsightsData/index.js
  src/components/InsightsData/useStyles.js
Labels: chore

#50 [HotFix] Set restrict mode to false
  next.config.js
Labels: bug

#41 [Chore] chromatic
  .github/workflows/chromatic.yml
  package.json
  src/components/DataVisuals/useStyles.js
  src/components/FeaturedStoryCard/useStyles.js
  src/components/InsightsData/useStyles.js
  src/components/Link/index.js
  src/components/Link/index.stories.js
  src/components/Menu/index.js
  src/components/Navigation/MobileNavigation/index.js
  src/config.js
  src/utils/site.js
  yarn.lock
Labels: dependencies, chore

#52 [Fix] Fonts
  public/fonts/poppins-v15-latin-100.eot
  public/fonts/poppins-v15-latin-100.svg
  public/fonts/poppins-v15-latin-100.ttf
  public/fonts/poppins-v15-latin-100.woff
  public/fonts/poppins-v15-latin-100.woff2
  public/fonts/poppins-v15-latin-200.eot
  public/fonts/poppins-v15-latin-200.svg
  public/fonts/poppins-v15-latin-200.ttf
  public/fonts/poppins-v15-latin-200.woff
  public/fonts/poppins-v15-latin-200.woff2
  public/fonts/poppins-v15-latin-800.eot
  public/fonts/poppins-v15-latin-800.ttf
  public/fonts/poppins-v15-latin-800.woff
  public/fonts/poppins-v15-latin-800.woff2
  public/fonts/poppins-v15-latin-italic.eot
  public/fonts/poppins-v15-latin-italic.svg
  public/fonts/poppins-v15-latin-italic.ttf
  public/fonts/poppins-v15-latin-italic.woff
  public/fonts/poppins-v15-latin-italic.woff2
  src/pages/_document.js
  src/theme/fonts.css
Labels: bug

#49 [Feature] Tabs
  src/components/Tabs/TabPanel.js
  src/components/Tabs/index.js
  src/components/Tabs/index.stories.js
  src/components/Tabs/useStyles.js
  src/theme/index.js
Labels: enhancement

#59 [Feature] Header
  src/components/AboutHero/index.js
  src/components/AboutHero/index.stories.js
  src/components/AboutHero/useStyles.js
  src/components/Header/index.js
  src/components/Header/index.stories.js
  src/components/Hero/index.js
  src/components/Hero/index.stories.js
  src/components/InsightsData/index.js
  src/components/InsightsData/useStyles.js
  src/components/OtherHero/index.js
  src/components/OtherHero/index.stories.js
  src/config.js
  src/theme/index.js
Labels: enhancement, Features

#51 Add news Section
  src/components/InsightCard/index.js
  src/components/Stories/CarouselItem.js
  src/components/Stories/index.js
  src/components/Stories/index.stories.js
  src/components/Stories/useStyles.js
  src/config.js
Labels: enhancement

#63 [Fix] Missing Poppins Medium
  public/fonts/poppins-v15-latin-500.eot
  public/fonts/poppins-v15-latin-500.svg
  public/fonts/poppins-v15-latin-500.ttf
  public/fonts/poppins-v15-latin-500.woff
  public/fonts/poppins-v15-latin-500.woff2
Labels: bug

#56 Stories Insights Section
  src/components/Card/index.js
  src/components/Card/useStyles.js
  src/components/InsightsData/index.js
  src/components/StoriesInsights/Content.js
  src/components/StoriesInsights/index.js
  src/components/StoriesInsights/index.stories.js
  src/components/StoriesInsights/useStyles.js
  src/functions/formatBlocksForSections.js
  src/functions/postTypes/processPostTypeQuery.js
  src/lib/wordpress/_query-partials/acfInsightsStoriesBlockFields.js
  src/lib/wordpress/pages/queryPageById.js
  src/pages/index.js
Labels: enhancement, dependencies

#65 [Fix] Heading Fonts
  src/components/DataVisuals/index.js
  src/components/DataVisuals/useStyles.js
  src/components/ExploreCard/index.js
  src/components/ExploreCard/useStyles.js
  src/components/ExploreOtherTools/index.js
  src/components/ExploreOtherTools/useStyles.js
  src/components/FeaturedStoryCard/index.js
  src/components/FeaturedStoryCard/index.stories.js
  src/components/FeaturedStoryCard/useStyles.js
  src/components/HowItWorks/useStyles.js
  src/components/InsightCard/index.js
  src/components/Newsletter/index.js
  src/components/Partners/Partners.js
  src/components/StoriesInsights/Content.js
  src/components/StoriesInsights/useStyles.js
  src/theme/index.js
Labels: enhancement

#47 [Feature] Summary
  src/components/Summary/index.js
  src/components/Summary/index.stories.js
  src/components/Summary/useStyles.js
  src/functions/formatBlockData.js
  src/pages/about.js
  src/pages/how-it-works.js
Labels: enhancement

#62 [Feature] Start Learning Block
  src/components/StartLearning/index.js
  src/components/StartLearning/index.stories.js
  src/pages/how-it-works.js
Labels: enhancement, Features

#61 Stories Landing page & Expanded Page
  .env.sample
  next.config.js
  package.json
  src/assets/icons/Group 3047.svg
  src/assets/icons/Group 3048.svg
  src/assets/icons/Group 3049.svg
  src/assets/icons/Group 3184.svg
  src/assets/icons/Group 4105.svg
  src/assets/icons/Group 4106.svg
  src/components/Card/index.js
  src/components/Card/useStyles.js
  src/components/FeaturedStoryCard/index.js
  src/components/FeaturedStoryCard/useStyles.js
  src/components/InsightCard/Content.js
  src/components/InsightCard/index.js
  src/components/InsightCard/useStyles.js
  src/components/InsightsData/index.js
  src/components/Partners/index.js
  src/components/ShareBar/ShareButton.js
  src/components/ShareBar/index.js
  src/components/ShareBar/index.stories.js
  src/components/ShareBar/useStyles.js
  src/components/Stories/CarouselItem.js
  src/components/Stories/index.js
  src/components/Stories/useStyles.js
  src/components/StoriesInsights/index.js
  src/components/StoriesInsights/useStyles.js
  src/components/StoriesNavigation/index.js
  src/components/StoryPage/StoryHeader.js
  src/components/StoryPage/index.js
  src/components/StoryPage/index.stories.js
  src/components/StoryPage/useStyles.js
  src/config.js
  src/functions/formatBlocksForSections.js
  src/functions/menus/formatHeirarchialMenu.js
  src/functions/postTypes/getPostTypeStaticPaths.js
  src/functions/postTypes/getPostTypeStaticProps.js
  src/functions/postTypes/getPostTypeTaxonomyArchive.js
  src/functions/postTypes/processPostTypeQuery.js
  src/lib/wordpress/_config/postTypes.js
  src/lib/wordpress/_query-partials/acfFeaturedStoriesBlockFields.js
  src/lib/wordpress/_query-partials/acfInsightsStoriesBlockFields.js
  src/lib/wordpress/_query-partials/categoriesPostFields.js
  src/lib/wordpress/_query-partials/lazyBlockInsightChartBlockFields.js
  src/lib/wordpress/categories/queryPostsByCategory.js
  src/lib/wordpress/posts/queryPostById.js
  src/lib/wordpress/posts/queryPostsArchive.js
  src/pages/api/wp/archive.js
  src/pages/stories/[[...slug]].js
  src/utils/fetchApi.js
  src/utils/formatStoryPosts.js
  yarn.lock
Labels: enhancement, dependencies

#69 [Fix] Our Partners
  src/components/DropdownSearch/index.stories.js
  src/components/Header/index.js
  src/components/Newsletter/index.js
  src/components/Partners/MainPartner.js
  src/components/Partners/Partners.js
  src/components/Partners/index.js
  src/components/Project/index.js
  src/components/Project/index.stories.js
  src/components/ProjectOwner/index.js
  src/components/ProjectOwner/index.stories.js
  src/components/ProjectPartners/index.js
  src/components/ProjectPartners/index.stories.js
  src/components/StoriesInsights/useStyles.js
  src/pages/about.js
  src/pages/how-it-works.js
  src/pages/index.js
  src/theme/index.js
Labels: bug, chore

#66 Add navigation cms
  src/components/Page/Base.js
  src/components/SocialMediaIcons/index.js
  src/config.js
  src/functions/menus/getNavigationMenu.js
  src/theme/index.js
Labels: enhancement, chore

#72 [Chore] Stories Page Improvement
  src/components/Card/index.js
  src/components/Card/useStyles.js
  src/components/InsightCard/useStyles.js
  src/components/Stories/CarouselItem.js
  src/components/Stories/index.js
  src/components/Stories/index.stories.js
  src/components/Stories/useStyles.js
  src/components/StoriesNavigation/index.js
  src/components/StoriesPage/index.js
  src/components/Tabs/index.js
  src/functions/getCategories.js
  src/lib/wordpress/categories/queryCategories.js
  src/pages/stories/[[...slug]].js
Labels: bug, chore

#70 [Feature] Add About Project Section
  src/assets/images/sat-mtKenya-2@2x.jpg
  src/components/AboutProject/index.js
  src/components/AboutProject/index.stories.js
  src/components/AboutProject/useStyles.js
  src/components/OtherHero/index.js
  src/components/OtherHero/index.stories.js
  src/pages/how-it-works.js
  src/theme/index.js
  src/utils/useProgressiveImage.js
Labels: enhancement

#29 [Feature] Data Indicators
  src/assets/icons/Group 4646-white.svg
  src/assets/icons/Group 4646.svg
  src/assets/icons/Group 4656-white.svg
  src/assets/icons/Group 4656.svg
  src/assets/icons/Group 4657-white.svg
  src/assets/icons/Group 4657.svg
  src/assets/icons/Group 4658-white.svg
  src/assets/icons/Group 4658.svg
  src/assets/icons/Group 4659-white.svg
  src/assets/icons/Group 4659.svg
  src/assets/images/Mask Group 8.png
  src/components/DataIndicators/Icon.js
  src/components/DataIndicators/index.js
  src/components/DataIndicators/index.stories.js
  src/components/DataIndicators/useStyles.js
  src/config.js
  src/functions/formatBlocksForSections.js
  src/pages/about.js
  src/pages/index.js
Labels: enhancement

#75 [Chore] Homepage
  src/pages/index.js
Labels: enhancement, chore

#67 Add Metrics
  src/assets/Component121.svg
  src/assets/Component122.svg
  src/assets/Metric1@2x.png
  src/assets/Metric2@2x.png
  src/components/Card/index.js
  src/components/Card/useStyles.js
  src/components/DataVisualCard/index.js
  src/components/DropdownSearch/index.js
  src/components/Metrics/index.js
  src/components/Metrics/index.stories.js
  src/components/Metrics/useStyles.js
  src/config.js
  src/functions/formatBlocksForSections.js
  src/pages/how-it-works.js
  src/theme/index.js
Labels: enhancement
