Repository CodeForAfrica/PesaYetu, pull requests merged in 2021-09, with the labels that each got.

#84 [Chore] Cards on the Table
  package.json
  src/components/AboutTeam/index.js
  src/components/AboutTeam/useStyles.js
  src/components/Card/ActionArea.js
  src/components/Card/Content.js
  src/components/Card/Media.js
  src/components/Card/index.js
  src/components/Card/index.stories.js
  src/components/Card/useStyles.js
  src/components/DataVisualCard/index.js
  src/components/DataVisualCard/index.stories.js
  src/components/DataVisualCard/useStyles.js
  src/components/DataVisualisationGuide/index.js
  src/components/DataVisualisationGuide/index.stories.js
  src/components/DataVisualisationGuide/useStyles.js
  src/components/DataVisuals/index.js
  src/components/ExploreCard/index.js
  src/components/ExploreCard/index.stories.js
  src/components/ExploreCard/useStyles.js
  src/components/ExploreOtherTools/index.js
  src/components/ExploreOtherTools/useStyles.js
  src/components/FeaturedStoryCard/index.js
  src/components/FeaturedStoryCard/useStyles.js
  src/components/Image/index.js
  src/components/InsightCard/Content.js
  src/components/InsightCard/index.js
  src/components/InsightCard/index.stories.js
  src/components/InsightCard/useStyles.js
  src/components/InsightsData/index.js
  src/components/Metrics/index.js
  src/components/Metrics/useStyles.js
  src/components/OurCourses/index.js
  src/components/Page/Base.js
  src/components/Stories/CarouselItem.js
  src/components/Stories/index.js
  src/components/Stories/useStyles.js
  src/components/StoriesInsights/Content.js
  src/components/StoriesInsights/index.js
  src/components/StoriesInsights/useStyles.js
  src/functions/formatBlocksForSections.js
  src/pages/index.js
  src/theme/index.js
  yarn.lock
Labels: enhancement, dependencies, chore

#85 [Chore] Merry-go-round
  src/components/AboutTeam/index.js
  src/components/AboutTeam/useStyles.js
  src/components/Card/Content.js
  src/components/Carousel/index.js
  src/components/Carousel/index.stories.js
  src/components/Carousel/useStyles.js
  src/components/DataVisualisationGuide/index.js
  src/components/DataVisualisationGuide/useStyles.js
  src/components/DatasetsAndDocuments/index.js
  src/components/ExploreOtherTools/index.js
  src/components/ExploreOtherTools/useStyles.js
  src/components/OurCourses/index.js
  src/components/OurCourses/useStyles.js
  src/components/Sources/CarouselItem.js
  src/components/Sources/index.js
  src/components/Sources/useStyles.js
  src/components/Stories/index.js
  src/components/Stories/useStyles.js
  src/components/StoriesInsights/CarouselDots.js
  src/components/StoriesInsights/CarouselItem.js
  src/components/StoriesInsights/index.js
  src/components/StoriesInsights/useStyles.js
Labels: chore

#87 [Fix] ClickAwayDon'tListen
  src/components/DataIndicators/IndicatorPanel.js
  src/components/DataIndicators/index.js
  src/components/DataIndicators/useStyles.js
Labels: bug, enhancement

#88 [HotFix] Card
  src/components/Card/ActionArea.js
  src/components/ExploreOtherTools/index.js
  src/components/ExploreOtherTools/useStyles.js
Labels: bug

#82 [Chore] Preview API
  src/pages/about.js
  src/pages/api/preview.js
Labels: chore

#89 Explore Map
  src/assets/icons/hover-icon.png
  src/components/ExplorePage/index.js
  src/components/HURUmap/LocationTag/index.js
  src/components/HURUmap/LocationTag/index.stories.js
  src/components/HURUmap/Map/Layers.js
  src/components/HURUmap/Map/index.js
  src/components/HURUmap/Map/index.stories.js
  src/components/Hero/Map/index.js
  src/components/Hero/index.js
  src/components/Page/Base.js
  src/functions/menus/getMenus.js
  src/pages/explore.js
  src/pages/explore/[[...slug]].js
  src/pages/index.js
  src/theme/index.js
  src/utils/fetchJson.js
Labels: bug, enhancement

#91 [HotFix] Optimize font loading
  src/pages/_document.js
  src/theme/fonts.css
Labels: bug, chore

#93 [HotFix] Update .env.sample to reflect recent changes
  .env.sample
Labels: bug, chore

#95 [Feature] Indicator Metrics
  src/components/HURUmap/KeyMetric/index.js
  src/components/HURUmap/KeyMetric/index.stories.js
  src/components/HURUmap/KeyMetric/useStyles.js
Labels: enhancement

#92 [HotFix] Fix Warning
  src/components/HURUmap/Map/Layers.js
Labels: bug, chore

#94 [Feature] Tutorial
  package.json
  src/assets/icons/Component 108 – 5.svg
  src/components/DropdownSearch/index.js
  src/components/HURUmap/Tutorial/Connector.js
  src/components/HURUmap/Tutorial/Line.js
  src/components/HURUmap/Tutorial/TutorialStep/index.js
  src/components/HURUmap/Tutorial/TutorialStep/useStyles.js
  src/components/HURUmap/Tutorial/index.js
  src/components/HURUmap/Tutorial/index.stories.js
  src/components/HURUmap/Tutorial/useStyles.js
  src/components/Navigation/ExploreNavigation/index.js
  src/config.js
  src/functions/formatBlocksForSections.js
  src/pages/explore/[[...slug]].js
  yarn.lock
Labels: enhancement

#96 [Feature] Location
  next.config.js
  src/components/ExplorePage/index.js
  src/components/HURUmap/KeyMetric/index.js
  src/components/HURUmap/KeyMetric/index.stories.js
  src/components/HURUmap/KeyMetric/useStyles.js
  src/components/HURUmap/Location/index.js
  src/components/HURUmap/Location/index.stories.js
  src/components/HURUmap/Location/useStyles.js
  src/components/HURUmap/LocationHighlight/index.js
  src/components/HURUmap/LocationHighlight/index.stories.js
  src/components/HURUmap/LocationHighlight/useStyles.js
  src/components/HURUmap/LocationTag/index.js
  src/components/HURUmap/LocationTag/index.stories.js
  src/components/HURUmap/Map/Layers.js
  src/components/HURUmap/Map/index.js
  src/components/HURUmap/Tutorial/index.stories.js
  src/components/Hero/Map/index.js
  src/components/Link/index.js
  src/components/Navigation/ExploreNavigation/index.js
  src/config.js
  src/pages/explore/[[...slug]].js
  src/utils/fetchProfile.js
Labels: enhancement, Features

#97 [Feature] Profile Category
  src/components/HURUmap/CategoryHeader/index.js
  src/components/HURUmap/CategoryHeader/index.stories.js
  src/components/HURUmap/CategoryHeader/useStyles.js
Labels: enhancement

#101 [Feature] Number Formatting
  package.json
  src/config.js
  src/utils/fetchProfile.js
  src/utils/formatNumericalValue.js
  yarn.lock
Labels: enhancement, dependencies

#99 [Feature] Location Header
  src/assets/icons/pin.svg
  src/assets/icons/print.svg
  src/components/HURUmap/LocationHeader/index.js
  src/components/HURUmap/LocationHeader/index.stories.js
  src/components/HURUmap/LocationHeader/useStyles.js
Labels: enhancement

#104 [Feature] AFRICA
  .env.sample
  src/components/DatasetsAndDocuments/index.stories.js
  src/components/DatasetsAndDocuments/useStyles.js
  src/components/Sources/CarouselItem.js
  src/components/Sources/index.js
  src/components/Sources/useStyles.js
  src/components/SourcesFilter/index.js
  src/components/SourcesFilter/input.js
  src/config.js
  src/functions/formatBlocksForSections.js
  src/pages/data/[[...slug]].js
  src/utils/fetchOpenAfricaDatasets.js
  src/utils/fetchSourceAfricaDocuments.js
Labels: enhancement, Features

#103 [Feature] SubCategory Header
  src/components/HURUmap/SubcategoryHeader/index.js
  src/components/HURUmap/SubcategoryHeader/index.stories.js
Labels: Features

#107 [Fix] Data page
  src/assets/icons/expand_more.svg
  src/components/DatasetsAndDocuments/index.js
  src/components/DatasetsAndDocuments/useStyles.js
  src/components/Sources/CarouselItem.js
  src/components/Sources/Dataset.js
  src/components/Sources/Document.js
  src/components/Sources/index.js
  src/components/Sources/useStyles.js
  src/components/SourcesFilter/index.js
  src/components/SourcesFilter/input.js
  src/pages/data/[[...slug]].js
  src/theme/index.js
Labels: bug

#98 [Feature] Panel Button Group
  src/assets/icons/Component 95 – 2.svg
  src/assets/icons/Component 96 – 12.svg
  src/assets/icons/Component 97 – 2.svg
  src/assets/icons/Component 98 – 2.svg
  src/assets/icons/kenya.svg
  src/assets/icons/location-pin.svg
  src/assets/icons/office-push-pin.svg
  src/assets/icons/pin.svg
  src/components/HURUmap/PanelButtonGroup/index.js
  src/components/HURUmap/PanelButtonGroup/index.stories.js
  src/components/HURUmap/PanelButtonGroup/useStyles.js
Labels: enhancement

#108 [Fix] Maintain Panel Button Border Radius
  src/components/HURUmap/PanelButtonGroup/useStyles.js
Labels: bug

#112 [Feature] How it works tooltip
  src/components/HURUmap/Tutorial/index.js
  src/components/Summary/index.js
  src/components/TooltipBanner/index.js
  src/pages/explore/[[...slug]].js
  src/pages/how-it-works.js
Labels: enhancement
