Repository CodeForAfrica/PesaYetu, pull requests merged in 2021-10, with the labels that each got.

#105 [Feature] Chart Filter
  src/components/HURUmap/ChartFilter/index.js
  src/components/HURUmap/ChartFilter/index.stories.js
  src/components/HURUmap/ChartFilter/useStyles.js
  src/components/Select/index.js
  src/components/Select/index.stories.js
  src/components/Select/useStyles.js
  src/components/SourcesFilter/index.js
Labels: Features

#110 [Fix ] otherHero component on tablet && desktop
  src/components/OtherHero/index.js
Labels: bug, enhancement

#90 Explore charts
  package.json
  src/assets/icons/Component 1.svg
  src/assets/icons/Component 108 – 1.svg
  src/assets/icons/Component 125 – 1.svg
  src/assets/icons/Component 27.svg
  src/assets/icons/Component1375.png
  src/assets/icons/Component1375.svg
  src/assets/icons/Component1375@2x.png
  src/assets/icons/Component852.svg
  src/assets/icons/action-close.svg
  src/assets/icons/chart-info.svg
  src/components/HURUmap/CategoryHeader/useStyles.js
  src/components/HURUmap/Chart/BarChartScope.js
  src/components/HURUmap/Chart/DonutChartScope.js
  src/components/HURUmap/Chart/LineChartScope.js
  src/components/HURUmap/Chart/StackedChartScope.js
  src/components/HURUmap/Chart/Tooltip.js
  src/components/HURUmap/Chart/TreeMapChartScope.js
  src/components/HURUmap/Chart/VerticalBarChartScope.js
  src/components/HURUmap/Chart/VerticalStackedChartScope.js
  src/components/HURUmap/Chart/configureScope.js
  src/components/HURUmap/Chart/index.js
  src/components/HURUmap/Chart/index.stories.js
  src/components/HURUmap/Chart/properties.js
  src/components/HURUmap/Chart/utils.js
  src/components/HURUmap/ChartTooltip/index.js
  src/components/HURUmap/ChartTooltip/index.stories.js
  src/components/HURUmap/IndicatorTitle/Action.js
  src/components/HURUmap/IndicatorTitle/Download.js
  src/components/HURUmap/IndicatorTitle/Share.js
  src/components/HURUmap/IndicatorTitle/index.js
  src/components/HURUmap/IndicatorTitle/useStyles.js
  src/components/HURUmap/Panel/RichData.js
  src/components/HURUmap/Panel/useStyles.js
  src/components/HURUmap/SubcategoryHeader/index.js
  src/pages/embed/[geoCode]/[chartId].js
  src/theme/index.js
  yarn.lock
Labels: enhancement

#115 [Feature] AWS S3 image upload api
  .env.sample
  next.config.js
  package.json
  src/pages/api/s3-upload.js
  yarn.lock
Labels: enhancement

#116 [Fix] VideoJS
  src/components/HowItWorks/Player.js
Labels: bug

#114 [Feature] Explore Mobile
  src/assets/icons/Component 130 – 1.svg
  src/assets/icons/caret.svg
  src/components/ExplorePage/index.js
  src/components/HURUmap/LocationHeader/index.js
  src/components/HURUmap/Panel/DesktopPanel/PanelItem.js
  src/components/HURUmap/Panel/DesktopPanel/RichData.js
  src/components/HURUmap/Panel/DesktopPanel/index.js
  src/components/HURUmap/Panel/DesktopPanel/useStyles.js
  src/components/HURUmap/Panel/MobilePanel/RichData.js
  src/components/HURUmap/Panel/MobilePanel/SubcategoryList.js
  src/components/HURUmap/Panel/MobilePanel/index.js
  src/components/HURUmap/Panel/MobilePanel/useStyles.js
  src/components/HURUmap/Panel/Profile.js
  src/components/HURUmap/Panel/RichData.js
  src/components/HURUmap/Panel/formatProfileDataIntoArray.js
  src/components/HURUmap/Panel/index.js
  src/components/Page/Base.js
  src/components/Tabs/index.js
  src/config.js
  src/functions/formatBlocksForSections.js
  src/pages/explore/[[...slug]].js
  yarn.lock
Labels: enhancement
