Repository CodeForAfrica/PesaYetu, pull requests merged in 2021-11, with the labels that each got.

#100 [Feature] Pin & Compare
  src/assets/Component 96 – 12.svg
  src/assets/Group 958.svg
  src/assets/icons/Component 108 – 1.svg
  src/assets/icons/Component 108-1.svg
  src/assets/icons/Component108-4.svg
  src/components/DropdownSearch/index.js
  src/components/ExplorePage/index.js
  src/components/HURUmap/Chart/LineChartScope.js
  src/components/HURUmap/Chart/StackedChartScope.js
  src/components/HURUmap/Chart/VerticalBarChartScope.js
  src/components/HURUmap/Chart/VerticalStackedChartScope.js
  src/components/HURUmap/Chart/index.js
  src/components/HURUmap/LocationHeader/index.js
  src/components/HURUmap/LocationHeader/useStyles.js
  src/components/HURUmap/LocationTag/index.js
  src/components/HURUmap/Map/Layers.js
  src/components/HURUmap/Map/index.js
  src/components/HURUmap/Panel/DesktopPanel/PanelItem.js
  src/components/HURUmap/Panel/DesktopPanel/index.js
  src/components/HURUmap/Panel/Profile.js
  src/components/HURUmap/Panel/formatProfileDataIntoArray.js
  src/components/HURUmap/Panel/index.js
  src/components/HURUmap/Panel/index.stories.js
  src/components/HURUmap/PanelButtonGroup/index.js
  src/components/HURUmap/PanelButtonGroup/useStyles.js
  src/components/HURUmap/PinAndCompare/index.js
  src/components/HURUmap/PinAndCompare/index.stories.js
  src/components/HURUmap/PinAndCompare/useStyles.js
  src/components/Navigation/MobileNavigation/index.js
  src/components/Select/index.js
  src/components/Select/useStyles.js
  src/config/index.js
  src/pages/explore/[[...slug]].js
  src/theme/index.js
Labels: enhancement, Features

#139 [Feature] Reusable Blocks
  src/functions/formatBlockData.js
  src/functions/formatBlocksForSections.js
  src/functions/getReusableBlockById.js
  src/lib/wordpress/blocks/queryReusableBlocks.js
Labels: enhancement

#140 Embed comparison charts + SEO fixes
  src/assets/logos/Group5002.svg
  src/components/Card/Content.js
  src/components/FeaturedStoryCard/index.js
  src/components/FeaturedStoryCard/useStyles.js
  src/components/HURUmap/Chart/Scope/index.js
  src/components/HURUmap/Chart/Scope/signals.js
  src/components/HURUmap/Chart/TreemapChartScope.js
  src/components/HURUmap/Chart/configureScope.js
  src/components/HURUmap/Chart/index.js
  src/components/HURUmap/IndicatorTitle/Download.js
  src/components/HURUmap/IndicatorTitle/Share.js
  src/components/HURUmap/Panel/Profile.js
  src/components/Page/Base.js
  src/components/Stories/CarouselItem.js
  src/components/Stories/useStyles.js
  src/components/StoryPage/index.js
  src/functions/formatBlocksForSections.js
  src/functions/getPagePropTypes.js
  src/lib/createChartImage.js
  src/lib/wordpress/_config/postTypes.js
  src/lib/wordpress/_query-partials/acfFeaturedStoriesBlockFields.js
  src/pages/about.js
  src/pages/embed/[geoCode]/[chartId].js
  src/pages/index.js
  src/pages/stories/[[...slug]].js
Labels: bug, enhancement

#141 [HotFix] Map Hover Cursor
  src/assets/icons/hover-icon.png
Labels: bug

#142 Update Layout Icons
  src/assets/icons/Group922.svg
  src/assets/icons/Group923.svg
  src/components/HURUmap/IndicatorTitle/Download.js
  src/components/HURUmap/IndicatorTitle/Share.js
  src/components/HURUmap/IndicatorTitle/useStyles.js
  src/config/index.js
Labels: enhancement

#143 [Hotfix] Undefined chart configuration
  src/components/HURUmap/Chart/Scope/signals.js
  src/components/HURUmap/Chart/index.js
  src/config/index.js
Labels: bug

#144 [Bug] Hide label on smaller rectangle - treemap
  src/components/HURUmap/Chart/DonutChartScope.js
  src/components/HURUmap/Chart/TreemapChartScope.js
  src/components/HURUmap/Chart/utils.js
  src/components/HURUmap/Panel/formatProfileDataIntoArray.js
  src/utils/slugify.js
Labels: bug
