Repository CodeForAfrica/PesaYetu, pull requests merged in 2022-06, with the labels that each got.

#202 Handle missing metadata in KeyMetric
  src/components/HURUmap/KeyMetric/index.js
Labels: bug

#203 CI for deployment to Dokku
  .dockerignore
  .github/workflows/build_deploy.yml
  .github/workflows/deploy.yml
  Dockerfile
  contrib/dokku/Dockerfile
  next.config.js
  package.json
Labels: chore

#205 Add open Africa and source Africa domains during image build stage
  .github/workflows/build_deploy.yml
  Dockerfile
  contrib/dokku/Dockerfile
  package.json
Labels: bug

#207 Add missing APP_URL in builder stage
  Dockerfile
  contrib/dokku/Dockerfile
  package.json
Labels: bug

#208 Improve Responsive
  contrib/dokku/Dockerfile
  package.json
  src/components/AboutTeam/index.js
  src/components/Hero/index.js
Labels: bug, enhancement
