Repository CodeForAfrica/PesaYetu, pull requests merged in 2022-02, with the labels that each got.

#159 [Chore] Remove Chromatic Integration
  .github/workflows/chromatic.yml
  package.json
  yarn.lock
Labels: chore

#164 Stories Pagination
  src/components/FeaturedStoryCard/index.js
  src/components/FeaturedStoryCard/useStyles.js
  src/components/Pagination/index.js
  src/components/Pagination/index.stories.js
  src/components/Stories/List.js
  src/components/Stories/index.js
  src/components/Stories/useStyles.js
  src/components/StoriesPage/index.js
  src/components/Tabs/index.js
  src/functions/postTypes/getPostTypeTaxonomyArchive.js
  src/lib/wordpress/_query-partials/archivePageInfo.js
  src/lib/wordpress/categories/queryPostsByCategory.js
  src/lib/wordpress/posts/queryPostsArchive.js
  src/pages/api/wp/archive.js
  src/pages/stories/[[...slug]].js
  src/utils/formatStoryPosts.js
Labels: enhancement, chore

#167 [Chores] Custom Author Name & Other chores
  src/components/Card/useStyles.js
  src/components/DropdownSearch/index.js
  src/components/ExploreOtherTools/index.js
  src/components/ExploreOtherTools/useStyles.js
  src/components/Hero/Map/index.js
  src/components/Hero/index.js
  src/components/Stories/List.js
  src/components/Stories/useStyles.js
  src/components/StoriesInsights/CarouselItem.js
  src/components/StoriesInsights/useStyles.js
  src/lib/wordpress/posts/queryPostById.js
  src/pages/stories/[[...slug]].js
Labels: bug, chore

#169 [Hotfix] Change Licence Name on Footer
  src/components/DropdownSearch/index.js
  src/config/index.js
Labels: bug

#163 [Chore] Explore Page Structure
  src/components/ExplorePage/index.js
  src/components/ExplorePage/useExplore.js
  src/components/ExplorePage/useProfileGeography.js
  src/components/ExplorePage/useStyles.js
  src/components/HURUmap/Panel/DesktopPanel/PanelButtons.js
  src/components/HURUmap/Panel/DesktopPanel/index.js
  src/components/HURUmap/Panel/DesktopPanel/useStyles.js
  src/components/HURUmap/Panel/Profile.js
  src/components/HURUmap/Panel/ProfileItems.js
  src/components/HURUmap/Panel/index.js
  src/config/index.js
  src/lib/hurumap/index.js
  src/pages/api/hurumap/geographies/[geoCode].js
  src/pages/api/hurumap/index.js
  src/pages/embed/[geoCode]/[chartId].js
  src/pages/explore/[[...slug]].js
  src/utils/fetchJson.js
  src/utils/fetchProfile.js
  src/utils/fetchProfileConfigurations.js
Labels: chore

#157 [Bug] Location Selection on Mobile
  src/components/DropdownSearch/index.js
  src/components/ExplorePage/index.js
  src/components/HURUmap/Map/index.js
  src/components/HURUmap/Panel/MobilePanel/RichData.js
  src/components/HURUmap/Panel/MobilePanel/index.js
  src/components/HURUmap/Panel/MobilePanel/useStyles.js
  src/components/HURUmap/Panel/Profile.js
  src/components/HURUmap/Panel/ProfileItems.js
  src/components/HURUmap/Panel/index.stories.js
  src/components/HURUmap/PinAndCompare/index.js
  src/components/HURUmap/PinAndCompare/useStyles.js
  src/components/Hero/Map/index.js
  src/components/Hero/index.js
  src/config/index.js
  src/functions/menus/getMenus.js
  src/lib/hurumap/index.js
  src/pages/embed/[geoCode]/[chartId].js
  src/pages/explore/[[...slug]].js
  src/pages/index.js
Labels: bug

#176 [Fix] Social media image
  .env.sample
  public/site.webmanifest
  src/components/HURUmap/IndicatorTitle/Download.js
  src/components/HURUmap/IndicatorTitle/Share.js
  src/config/index.js
  src/lib/createChartImage.js
  src/pages/_document.js
  src/pages/embed/[geoCode]/[chartId].js
Labels: bug

#177 [Chore] Metrics positon and Indicator Description
  src/components/HURUmap/IndicatorTitle/index.js
  src/components/HURUmap/Panel/DesktopPanel/PanelButtons.js
  src/components/HURUmap/Panel/Profile.js
  src/components/HURUmap/Panel/ProfileItems.js
  src/components/HURUmap/TreeView/index.js
  src/components/Loading/index.js
  src/components/Loading/index.stories.js
  src/components/Stories/index.js
Labels: bug, chore
