Repository CodeForAfrica/PesaYetu, pull requests merged in 2022-03, with the labels that each got.

#179 [Fix] Sorting donut chart + axis ticks count
  src/components/HURUmap/Chart/BarChartScope.js
  src/components/HURUmap/Chart/DonutChartScope.js
  src/components/HURUmap/Chart/LineChartScope.js
  src/components/HURUmap/Chart/MultiLineChartScope.js
  src/components/HURUmap/Chart/Scope/signals.js
  src/components/HURUmap/Chart/StackedChartScope.js
  src/components/StoriesPage/index.js
  src/components/Tabs/index.js
Labels: bug, enhancement

#178 [Feature] Add copy icon to share + stories
  package.json
  src/assets/icons/Group 5062.svg
  src/assets/icons/closing-tag.svg
  src/components/HURUmap/IndicatorTitle/Share.js
  src/components/HURUmap/IndicatorTitle/useStyles.js
  src/components/ShareBar/ShareButton.js
  src/components/ShareBar/index.js
  src/components/ShareBar/index.stories.js
  src/components/ShareBar/useStyles.js
  yarn.lock
Labels: enhancement

#182 [Bug] Error handling unrecognised filter value
  src/components/HURUmap/Chart/index.js
  src/components/HURUmap/Chart/index.stories.js
Labels: bug, chore

#183 Metric source
  src/components/HURUmap/Chart/index.js
  src/components/HURUmap/KeyMetric/index.js
  src/components/HURUmap/KeyMetric/useStyles.js
  src/components/HURUmap/Source/index.js
  src/components/HURUmap/Source/index.stories.js
Labels: enhancement

#184 [FIX] SEO
  next-seo.config.js
  public/image.jpg
  src/components/Page/Base.js
  src/lib/createChartImage.js
  src/pages/embed/[geoCode]/[chartId].js
Labels: bug, enhancement

#180 [Fix] Stories pagiantion
  src/components/Pagination/index.js
  src/components/Stories/index.js
  src/components/StoriesPage/index.js
  src/components/Tabs/TabPanel.js
  src/components/Tabs/index.js
  src/functions/postTypes/getPostTypeStaticPaths.js
  src/functions/postTypes/getPostTypeStaticProps.js
  src/functions/postTypes/getPostTypeTaxonomyArchive.js
  src/pages/api/wp/archive.js
  src/pages/stories/[[...slug]].js
  src/utils/formatStoryPosts.js
Labels: bug

#185 Fix Chart Download Image
  src/components/Card/Media.js
  src/components/HURUmap/Chart/Filters.js
  src/components/HURUmap/Chart/Scope/signals.js
  src/components/HURUmap/Chart/index.js
  src/components/HURUmap/IndicatorTitle/Download.js
  src/components/HURUmap/IndicatorTitle/Share.js
  src/components/HURUmap/IndicatorTitle/index.js
Labels: bug

#186 Fix Extra spaces on embed iframe
  src/components/HURUmap/Chart/index.js
  src/components/HURUmap/IndicatorTitle/Share.js
  src/components/StoriesInsights/useStyles.js
Labels: bug

#187 Remove hovericon on charts
  src/assets/icons/Component1375.png
  src/assets/icons/Component1375.svg
  src/assets/icons/Component1375@2x.png
  src/components/HURUmap/Chart/Scope/signals.js
Labels: chore

#188 [Chore] Line time series + sorting ordinals
  .gitignore
  src/components/HURUmap/Chart/DonutChartScope.js
  src/components/HURUmap/Chart/LineChartScope.js
  src/components/HURUmap/Chart/MultiLineChartScope.js
  src/components/HURUmap/Chart/StackedChartScope.js
Labels: bug, chore
